### ISSUE TITLE
Difference between MOVI-A and MOVI

### ISSUE THREAD

**Issue by hnyu** [google-research/slot-attention-video#18]
Hi, 

In the README, it's said that MOVI-A is "of slightly higher complexity (e.g., more variation in backgrounds)", compared to the original MOVI dataset used in the ICLR2022 SAVI paper. Can you further elaborate on the exact differences between the two?

The reason why I'm asking about this is that, if I tried comparing the background of these two datasets by looking at some example frames (MOVI examples are taken from the paper figures), indeed I couldn't see much a difference. 

However, I've run SAVI and also baselines like SIMONe and SCALOR in the *unconditional, unsupervised (rgb prediction)* setting. The results I got on MOVI-A were worse than those reported in Table A.2. The gaps, in a consistent way, are about 0.15~0.2 regarding FG-ARI for all the three methods. (From my understanding, Table A.2 is in the unconditional, unsupervised setting for SIMONe and SCALOR if their original setups were used.)

I can't imagine that a slight difference in background between MOVI and MOVI-A could contribute to such a large gap in FG-ARI. So are there any other differences between the two datasets, or do I have a misunderstanding regarding the experiment setting and Table A.2? Thanks!

**Comment by tkipf** [comment]
Thanks a lot for your question. Several settings changed between the original MOVi and the new MOVi-A dataset, so it's difficult to point exactly to the reason for the discrepancy. The comment on higher background complexity refers to the MOVi-C vs. MOVi++ datasets, i.e. this does not affect MOVi/MOVi-A.

The difference you're seeing could also be related to minor differences in your baseline implementations from the ones we used. For SCALOR we used the implementation provided by the authors (with hyperparameters stated in our appendix) while for SIMONe we did a best-effort attempt at reimplementing the model (roughly matching performance reported in the SIMONe paper on CATER), i.e. there are likely some small differences which could have an impact on other datasets.

FG-ARI is a relatively sensitive metric and all baseline models essentially fall short of modeling (unconditional) MOVi/MOVi-A successfully, so I wouldn't worry about 0.1-0.2 FG-ARI difference (since it still amounts to failure of the model, and the degree of failure is not very meaningful).

**Comment by hnyu** [comment]
@tkipf Thanks for your quick reply! 

Yeah, I did use the suggested hyperparameters in your appendix for SCALOR (except that I found an 8x8 grid is much better than a 4x4 grid), and the SIMONe implementation I used also got matching performance on CATER. 

Regarding your last comment on all models falling short of modeling MOVi/MOVi-A in the unconditional setting, can you elaborate on this further in case I have a misunderstanding? Do you think that any FG-ARI number not close to 1 indicates a failure (SCALOR was reported to have 0.81 FG-ARI which I think is quite impressive)? Thanks again for your answer!

**Comment by tkipf** [comment]
Ah yes, you're right. I misremembered the performance of these methods in the unconditional setting on MOVi. They do fail on MOVi++ (MOVi-C) but indeed the performance on MOVi is quite OK.

**Comment by hnyu** [comment]
> Ah yes, you're right. I misremembered the performance of these methods in the unconditional setting on MOVi. They do fail on MOVi++ (MOVi-C) but indeed the performance on MOVi is quite OK.

Thanks for your clarification!
